### ISSUE TITLE
Proposed as severance

### ISSUE THREAD

**Issue by starsep** [dabreegster/severance_snape#6]
I noticed that highway=proposed ways are marked as severance.
I suspect that's not intended

**Comment by dabreegster** [comment]
Hmm, you're probably right. But if there's construction there and it's hard to cross in the meantime, it might still act as a severance when walking around if it's long enough. Happen to have a link / screenshot of the example you found?

**Comment by starsep** [comment]
Example: https://osm.org/way/1157187102
At the moment there is no construction there. Which is why it's mapped as highway=proposed instead of highway=construction 
![image](https://github.com/dabreegster/severance_snape/assets/2798728/214d4387-c4ea-4bec-a763-864c60b2cf20)

**Comment by dabreegster** [comment]
Thank you, I forgot that there's a difference between those two! Fixed:
![Screenshot from 2024-01-14 14-56-50](https://github.com/dabreegster/severance_snape/assets/1664407/f7a07a31-deb2-4b19-815f-63e909469927)

I'll try and clean up this app and add some instructions soon. It's still quite experimental, but maybe shows interesting problems (after more OSM parsing bugs are fixed)
